services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '${DB_PORT}:5432' 
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - '${REDIS_PORT}:6379' 

volumes:
  postgres_data: